# Generated by Django 4.1.4 on 2022-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("article", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In stock"),
                            ("under_order", "Under the order"),
                            ("admisson", "Expecting admission"),
                            ("not_in_stock", "Not in the stock"),
                            ("not_manufacturing", "Not manifacturing"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
